apiPort: 4455
webPort: 4456
versionPort: 4457
maintenanceStatus: 'maintenance_out'

#          'n-production-game-api.sekai-en.com'
apiDomain: 'libre-sekai-game-api.rustyraven.pw'

#          'n-production-web.sekai-en.com'
webDomain: 'sekai-web-files.rustyraven.pw' # must be 29 characters long

versions:
  - systemProfile: 'production'
    appVersion: '5.0.5'
    multiPlayVersion: 'len'
    assetVersion: '5.0.51.0'
    appVersionStatus: 'available'

latestVersion: 0

legal:
  privacyPolicy: 'https://rustyraven.pw'
  termsOfUse: 'https://rustyraven.pw'

informations:
  - id: 1
    seq: 1
    informationType: normal
    informationTag: information 
    browseType: 'external'
    platform: 'all'
    title: 'Welcome to libresekai powered server!'
    path: 'https://github.com/ryotairi/libresekai'
    startAt: 0

initialPlayerName: 'SEKAI Player'

initialFreeCards: [81, 89, 93, 97, 101, 105] # No idea on what these are for, but they were in registration response body. I've picked Leo/need btw
initialMusics:
- 1 # Tell Your World
- 2 # ROKI (Leo/need)
- 10 # Happy Synthesizer (MORE MORE JUMP)
- 26 # Bring It On (Vivid BAD SQUAD)
- 41 # Sweet Magic (Wonderlands x Showtime)
- 50 # Blessing (VOCALOIDS)
- 51 # The World Hasn't Even Started Yet (Wonderlands x Showtime)
- 54 # Ready Steady (Vivid BAD SQUAD)
- 57 # Newly Edgy Idols (More More Jump)
- 60 # Composing the Future (Nightcord at 25:00)
- 67 # Jishoumushoku (Nightcord at 25:00)
- 76 # SEKAI (iirc its anniversary song)
- 77 # Wah wah world
- 82 # alive